"""UI string localisation.

Common languages ship with hand-written translations so the interface is
instant. Any other language is translated on first request through the same
DeepSeek backend and then cached -- so "almost any language" just works.
"""
import asyncio
from typing import Dict

import languages
import translation

# --- Source of truth: English ------------------------------------------- #
EN = {
    "appName": "LinguaRoom",
    "tagline": "Chat in every language",
    "yourName": "Your name",
    "namePlaceholder": "e.g. Maria",
    "selectLanguage": "Select your language",
    "languagePlaceholder": "Search languages…",
    "createRoom": "Create room",
    "joinRoom": "Join room",
    "joinTitle": "Join a room",
    "joinSubtitle": "Enter a room code to start chatting",
    "roomCode": "Room code",
    "shareTitle": "Invite people",
    "shareSubtitle": "Share this link — everyone picks their own language",
    "copyLink": "Copy invite link",
    "copied": "Copied!",
    "members": "Members",
    "you": "You",
    "online": "online",
    "messagePlaceholder": "Type a message…",
    "send": "Send",
    "typing": "typing…",
    "showOriginal": "Show original",
    "hideOriginal": "Hide original",
    "original": "Original",
    "translated": "Translated",
    "leave": "Leave",
    "connecting": "Connecting…",
    "disconnected": "Disconnected",
    "reconnect": "Reconnect",
    "welcome": "Welcome to the room",
    "shareHint": "Share the link so friends can join in their language",
    "justNow": "just now",
    "today": "Today",
    "yesterday": "Yesterday",
    "back": "Back",
    "invalidName": "Please enter a name",
    "invalidLang": "Please select a language",
    "translationUnavailable": "Translation unavailable",
    "poweredBy": "Translated by DeepSeek (free)",
    "joinCta": "Enter",
    "searchLanguages": "Search languages…",
    "heroTitle": "Chat with the whole world.",
    "heroSub": "Create a room, pick your language and share the link. Every message is translated live into each person’s language — names, links and code stay intact.",
    "feat1Title": "Interface in your language",
    "feat1Desc": "The whole app is translated automatically.",
    "feat2Title": "Real-time AI translation",
    "feat2Desc": "Everyone sees messages in their own language.",
    "feat3Title": "~70 languages",
    "feat3Desc": "Share a link — friends join in their language.",
    "noAccount": "No account needed · Open source · Translated with DeepSeek",
}

# --- Hand-written built-ins for the most common languages --------------- #
BUILTIN = {
    "de": {
        "tagline": "Chatte in jeder Sprache", "yourName": "Dein Name",
        "namePlaceholder": "z. B. Maria", "selectLanguage": "Wähle deine Sprache",
        "languagePlaceholder": "Sprachen suchen…", "createRoom": "Raum erstellen",
        "joinRoom": "Raum beitreten", "joinTitle": "Raum beitreten",
        "joinSubtitle": "Gib einen Raum-Code ein, um zu chatten",
        "roomCode": "Raum-Code", "shareTitle": "Leute einladen",
        "shareSubtitle": "Teile diesen Link — jeder wählt seine eigene Sprache",
        "copyLink": "Einladungslink kopieren", "copied": "Kopiert!",
        "members": "Mitglieder", "you": "Du", "online": "online",
        "messagePlaceholder": "Nachricht schreiben…", "send": "Senden",
        "typing": "schreibt…", "showOriginal": "Original anzeigen",
        "hideOriginal": "Original ausblenden", "original": "Original",
        "translated": "Übersetzt", "leave": "Verlassen",
        "connecting": "Verbinde…", "disconnected": "Verbindung getrennt",
        "reconnect": "Neu verbinden", "welcome": "Willkommen im Raum",
        "shareHint": "Teile den Link, damit Freunde in ihrer Sprache beitreten",
        "justNow": "gerade eben", "today": "Heute", "yesterday": "Gestern",
        "back": "Zurück", "invalidName": "Bitte gib einen Namen ein",
        "invalidLang": "Bitte wähle eine Sprache",
        "translationUnavailable": "Übersetzung nicht verfügbar",
        "poweredBy": "Übersetzt von DeepSeek (kostenlos)",
        "joinCta": "Betreten", "searchLanguages": "Sprachen suchen…",
        "heroTitle": "Chatte mit der ganzen Welt.",
        "heroSub": "Erstelle einen Raum, wähle deine Sprache und teile den Link. Jede Nachricht wird live in die Sprache der anderen übersetzt – Namen, Links und Code bleiben erhalten.",
        "feat1Title": "Oberfläche in deiner Sprache",
        "feat1Desc": "Die ganze App wird automatisch übersetzt.",
        "feat2Title": "KI-Übersetzung in Echtzeit",
        "feat2Desc": "Jeder sieht die Nachrichten in seiner eigenen Sprache.",
        "feat3Title": "~70 Sprachen",
        "feat3Desc": "Teile einen Link – Freunde treten in ihrer Sprache bei.",
        "noAccount": "Kein Account nötig · Open Source · Übersetzt mit DeepSeek",
    },
    "es": {
        "tagline": "Chatea en cualquier idioma", "yourName": "Tu nombre",
        "namePlaceholder": "p. ej. María", "selectLanguage": "Elige tu idioma",
        "languagePlaceholder": "Buscar idiomas…", "createRoom": "Crear sala",
        "joinRoom": "Unirse a la sala", "joinTitle": "Unirse a una sala",
        "joinSubtitle": "Introduce un código de sala para chatear",
        "roomCode": "Código de sala", "shareTitle": "Invita a personas",
        "shareSubtitle": "Comparte este enlace — cada uno elige su idioma",
        "copyLink": "Copiar enlace de invitación", "copied": "¡Copiado!",
        "members": "Miembros", "you": "Tú", "online": "en línea",
        "messagePlaceholder": "Escribe un mensaje…", "send": "Enviar",
        "typing": "escribiendo…", "showOriginal": "Ver original",
        "hideOriginal": "Ocultar original", "original": "Original",
        "translated": "Traducido", "leave": "Salir",
        "connecting": "Conectando…", "disconnected": "Desconectado",
        "reconnect": "Reconectar", "welcome": "Bienvenido a la sala",
        "shareHint": "Comparte el enlace para que tus amigos se unan en su idioma",
        "justNow": "ahora mismo", "today": "Hoy", "yesterday": "Ayer",
        "back": "Atrás", "invalidName": "Introduce un nombre",
        "invalidLang": "Selecciona un idioma",
        "translationUnavailable": "Traducción no disponible",
        "poweredBy": "Traducido por DeepSeek (gratis)",
        "joinCta": "Entrar", "searchLanguages": "Buscar idiomas…",
    },
    "fr": {
        "tagline": "Discuter dans toutes les langues", "yourName": "Votre nom",
        "namePlaceholder": "ex. Marie", "selectLanguage": "Choisissez votre langue",
        "languagePlaceholder": "Rechercher des langues…", "createRoom": "Créer une salle",
        "joinRoom": "Rejoindre la salle", "joinTitle": "Rejoindre une salle",
        "joinSubtitle": "Saisissez un code de salle pour discuter",
        "roomCode": "Code de salle", "shareTitle": "Inviter des personnes",
        "shareSubtitle": "Partagez ce lien — chacun choisit sa langue",
        "copyLink": "Copier le lien d'invitation", "copied": "Copié !",
        "members": "Membres", "you": "Vous", "online": "en ligne",
        "messagePlaceholder": "Écrivez un message…", "send": "Envoyer",
        "typing": "écrit…", "showOriginal": "Voir l'original",
        "hideOriginal": "Masquer l'original", "original": "Original",
        "translated": "Traduit", "leave": "Quitter",
        "connecting": "Connexion…", "disconnected": "Déconnecté",
        "reconnect": "Reconnexion", "welcome": "Bienvenue dans la salle",
        "shareHint": "Partagez le lien pour que vos amis rejoignent dans leur langue",
        "justNow": "à l'instant", "today": "Aujourd'hui", "yesterday": "Hier",
        "back": "Retour", "invalidName": "Veuillez saisir un nom",
        "invalidLang": "Veuillez choisir une langue",
        "translationUnavailable": "Traduction indisponible",
        "poweredBy": "Traduit par DeepSeek (gratuit)",
        "joinCta": "Entrer", "searchLanguages": "Rechercher des langues…",
    },
    "pt": {
        "tagline": "Converse em qualquer idioma", "yourName": "Seu nome",
        "namePlaceholder": "ex. Maria", "selectLanguage": "Selecione seu idioma",
        "languagePlaceholder": "Buscar idiomas…", "createRoom": "Criar sala",
        "joinRoom": "Entrar na sala", "joinTitle": "Entrar em uma sala",
        "joinSubtitle": "Digite um código de sala para conversar",
        "roomCode": "Código da sala", "shareTitle": "Convidar pessoas",
        "shareSubtitle": "Compartilhe este link — cada um escolhe seu idioma",
        "copyLink": "Copiar link de convite", "copied": "Copiado!",
        "members": "Membros", "you": "Você", "online": "online",
        "messagePlaceholder": "Digite uma mensagem…", "send": "Enviar",
        "typing": "digitando…", "showOriginal": "Ver original",
        "hideOriginal": "Ocultar original", "original": "Original",
        "translated": "Traduzido", "leave": "Sair",
        "connecting": "Conectando…", "disconnected": "Desconectado",
        "reconnect": "Reconectar", "welcome": "Bem-vindo à sala",
        "shareHint": "Compartilhe o link para seus amigos entrarem no seu idioma",
        "justNow": "agora mesmo", "today": "Hoje", "yesterday": "Ontem",
        "back": "Voltar", "invalidName": "Digite um nome",
        "invalidLang": "Selecione um idioma",
        "translationUnavailable": "Tradução indisponível",
        "poweredBy": "Traduzido por DeepSeek (grátis)",
        "joinCta": "Entrar", "searchLanguages": "Buscar idiomas…",
    },
    "it": {
        "tagline": "Chatta in ogni lingua", "yourName": "Il tuo nome",
        "namePlaceholder": "es. Maria", "selectLanguage": "Scegli la tua lingua",
        "languagePlaceholder": "Cerca lingue…", "createRoom": "Crea stanza",
        "joinRoom": "Unisciti alla stanza", "joinTitle": "Unisciti a una stanza",
        "joinSubtitle": "Inserisci un codice stanza per chattare",
        "roomCode": "Codice stanza", "shareTitle": "Invita persone",
        "shareSubtitle": "Condividi questo link — ciascuno sceglie la propria lingua",
        "copyLink": "Copia il link d'invito", "copied": "Copiato!",
        "members": "Membri", "you": "Tu", "online": "online",
        "messagePlaceholder": "Scrivi un messaggio…", "send": "Invia",
        "typing": "sta scrivendo…", "showOriginal": "Mostra originale",
        "hideOriginal": "Nascondi originale", "original": "Originale",
        "translated": "Tradotto", "leave": "Esci",
        "connecting": "Connessione…", "disconnected": "Disconnesso",
        "reconnect": "Riconnetti", "welcome": "Benvenuto nella stanza",
        "shareHint": "Condividi il link per far entrare gli amici nella loro lingua",
        "justNow": "proprio ora", "today": "Oggi", "yesterday": "Ieri",
        "back": "Indietro", "invalidName": "Inserisci un nome",
        "invalidLang": "Seleziona una lingua",
        "translationUnavailable": "Traduzione non disponibile",
        "poweredBy": "Tradotto da DeepSeek (gratis)",
        "joinCta": "Entra", "searchLanguages": "Cerca lingue…",
    },
    "nl": {
        "tagline": "Chat in elke taal", "yourName": "Jouw naam",
        "namePlaceholder": "bijv. Maria", "selectLanguage": "Kies je taal",
        "languagePlaceholder": "Talen zoeken…", "createRoom": "Ruimte aanmaken",
        "joinRoom": "Deelnemen aan ruimte", "joinTitle": "Doe mee met een ruimte",
        "joinSubtitle": "Voer een ruimtecode in om te chatten",
        "roomCode": "Ruimtecode", "shareTitle": "Mensen uitnodigen",
        "shareSubtitle": "Deel deze link — iedereen kiest zijn eigen taal",
        "copyLink": "Uitnodigingslink kopiëren", "copied": "Gekopieerd!",
        "members": "Leden", "you": "Jij", "online": "online",
        "messagePlaceholder": "Typ een bericht…", "send": "Versturen",
        "typing": "typt…", "showOriginal": "Toon origineel",
        "hideOriginal": "Verberg origineel", "original": "Origineel",
        "translated": "Vertaald", "leave": "Verlaten",
        "connecting": "Verbinden…", "disconnected": "Verbinding verbroken",
        "reconnect": "Opnieuw verbinden", "welcome": "Welkom in de ruimte",
        "shareHint": "Deel de link zodat vrienden in hun taal kunnen deelnemen",
        "justNow": "net nu", "today": "Vandaag", "yesterday": "Gisteren",
        "back": "Terug", "invalidName": "Voer een naam in",
        "invalidLang": "Selecteer een taal",
        "translationUnavailable": "Vertaling niet beschikbaar",
        "poweredBy": "Vertaald door DeepSeek (gratis)",
        "joinCta": "Betreden", "searchLanguages": "Talen zoeken…",
    },
    "ru": {
        "tagline": "Общайтесь на любом языке", "yourName": "Ваше имя",
        "namePlaceholder": "напр. Мария", "selectLanguage": "Выберите язык",
        "languagePlaceholder": "Поиск языков…", "createRoom": "Создать комнату",
        "joinRoom": "Войти в комнату", "joinTitle": "Войти в комнату",
        "joinSubtitle": "Введите код комнаты, чтобы начать общение",
        "roomCode": "Код комнаты", "shareTitle": "Пригласить людей",
        "shareSubtitle": "Поделитесь ссылкой — каждый выбирает свой язык",
        "copyLink": "Копировать ссылку-приглашение", "copied": "Скопировано!",
        "members": "Участники", "you": "Вы", "online": "в сети",
        "messagePlaceholder": "Введите сообщение…", "send": "Отправить",
        "typing": "печатает…", "showOriginal": "Показать оригинал",
        "hideOriginal": "Скрыть оригинал", "original": "Оригинал",
        "translated": "Переведено", "leave": "Выйти",
        "connecting": "Подключение…", "disconnected": "Соединение разорвано",
        "reconnect": "Переподключить", "welcome": "Добро пожаловать в комнату",
        "shareHint": "Поделитесь ссылкой, чтобы друзья присоединились на своём языке",
        "justNow": "только что", "today": "Сегодня", "yesterday": "Вчера",
        "back": "Назад", "invalidName": "Введите имя",
        "invalidLang": "Выберите язык",
        "translationUnavailable": "Перевод недоступен",
        "poweredBy": "Переведено DeepSeek (бесплатно)",
        "joinCta": "Войти", "searchLanguages": "Поиск языков…",
    },
    "zh": {
        "tagline": "用任何语言聊天", "yourName": "你的名字",
        "namePlaceholder": "例如 玛丽", "selectLanguage": "选择你的语言",
        "languagePlaceholder": "搜索语言…", "createRoom": "创建房间",
        "joinRoom": "加入房间", "joinTitle": "加入房间",
        "joinSubtitle": "输入房间码即可开始聊天", "roomCode": "房间码",
        "shareTitle": "邀请好友", "shareSubtitle": "分享此链接 —— 每个人选择自己的语言",
        "copyLink": "复制邀请链接", "copied": "已复制！",
        "members": "成员", "you": "你", "online": "在线",
        "messagePlaceholder": "输入消息…", "send": "发送",
        "typing": "正在输入…", "showOriginal": "显示原文",
        "hideOriginal": "隐藏原文", "original": "原文",
        "translated": "已翻译", "leave": "离开",
        "connecting": "连接中…", "disconnected": "已断开连接",
        "reconnect": "重新连接", "welcome": "欢迎来到房间",
        "shareHint": "分享链接，让朋友用他们的语言加入", "justNow": "刚刚",
        "today": "今天", "yesterday": "昨天", "back": "返回",
        "invalidName": "请输入名字", "invalidLang": "请选择语言",
        "translationUnavailable": "翻译不可用", "poweredBy": "由 DeepSeek（免费）翻译",
        "joinCta": "进入", "searchLanguages": "搜索语言…",
    },
    "ja": {
        "tagline": "どの言語でもチャット", "yourName": "あなたの名前",
        "namePlaceholder": "例：マリア", "selectLanguage": "言語を選択",
        "languagePlaceholder": "言語を検索…", "createRoom": "ルームを作成",
        "joinRoom": "ルームに参加", "joinTitle": "ルームに参加",
        "joinSubtitle": "ルームコードを入力してチャットを始めよう",
        "roomCode": "ルームコード", "shareTitle": "友達を招待",
        "shareSubtitle": "このリンクを共有 — 各自の言語を選べます",
        "copyLink": "招待リンクをコピー", "copied": "コピーしました！",
        "members": "メンバー", "you": "あなた", "online": "オンライン",
        "messagePlaceholder": "メッセージを入力…", "send": "送信",
        "typing": "入力中…", "showOriginal": "原文を表示",
        "hideOriginal": "原文を隠す", "original": "原文",
        "translated": "翻訳済み", "leave": "退出",
        "connecting": "接続中…", "disconnected": "切断されました",
        "reconnect": "再接続", "welcome": "ルームへようこそ",
        "shareHint": "リンクを共有して、友達が自分の言語で参加できるように",
        "justNow": "たった今", "today": "今日", "yesterday": "昨日",
        "back": "戻る", "invalidName": "名前を入力してください",
        "invalidLang": "言語を選択してください",
        "translationUnavailable": "翻訳は利用できません",
        "poweredBy": "DeepSeek（無料）によって翻訳",
        "joinCta": "参加", "searchLanguages": "言語を検索…",
    },
    "ko": {
        "tagline": "어떤 언어로든 채팅하세요", "yourName": "이름",
        "namePlaceholder": "예: 마리아", "selectLanguage": "언어 선택",
        "languagePlaceholder": "언어 검색…", "createRoom": "방 만들기",
        "joinRoom": "방 참여", "joinTitle": "방 참여",
        "joinSubtitle": "채팅하려면 방 코드를 입력하세요", "roomCode": "방 코드",
        "shareTitle": "친구 초대", "shareSubtitle": "이 링크를 공유하세요 — 각자 언어를 선택합니다",
        "copyLink": "초대 링크 복사", "copied": "복사됨!",
        "members": "멤버", "you": "나", "online": "온라인",
        "messagePlaceholder": "메시지를 입력하세요…", "send": "보내기",
        "typing": "입력 중…", "showOriginal": "원문 보기",
        "hideOriginal": "원문 숨기기", "original": "원문",
        "translated": "번역됨", "leave": "나가기",
        "connecting": "연결 중…", "disconnected": "연결 끊김",
        "reconnect": "다시 연결", "welcome": "방에 오신 것을 환영합니다",
        "shareHint": "링크를 공유해 친구들이 자신의 언어로 참여하게 하세요",
        "justNow": "방금", "today": "오늘", "yesterday": "어제",
        "back": "뒤로", "invalidName": "이름을 입력하세요",
        "invalidLang": "언어를 선택하세요",
        "translationUnavailable": "번역 사용 불가",
        "poweredBy": "DeepSeek(무료)로 번역됨",
        "joinCta": "입장", "searchLanguages": "언어 검색…",
    },
    "tr": {
        "tagline": "Her dilde sohbet et", "yourName": "Adınız",
        "namePlaceholder": "ör. Maria", "selectLanguage": "Dilinizi seçin",
        "languagePlaceholder": "Dil ara…", "createRoom": "Oda oluştur",
        "joinRoom": "Odaya katıl", "joinTitle": "Bir odaya katıl",
        "joinSubtitle": "Sohbet etmek için bir oda kodu girin", "roomCode": "Oda kodu",
        "shareTitle": "Kişi davet et", "shareSubtitle": "Bu bağlantıyı paylaşın — herkes kendi dilini seçer",
        "copyLink": "Davet bağlantısını kopyala", "copied": "Kopyalandı!",
        "members": "Üyeler", "you": "Sen", "online": "çevrimiçi",
        "messagePlaceholder": "Bir mesaj yazın…", "send": "Gönder",
        "typing": "yazıyor…", "showOriginal": "Orijinali göster",
        "hideOriginal": "Orijinali gizle", "original": "Orijinal",
        "translated": "Çevrildi", "leave": "Ayrıl",
        "connecting": "Bağlanıyor…", "disconnected": "Bağlantı kesildi",
        "reconnect": "Yeniden bağlan", "welcome": "Odaya hoş geldiniz",
        "shareHint": "Arkadaşlarınızın kendi dillerinde katılması için bağlantıyı paylaşın",
        "justNow": "az önce", "today": "Bugün", "yesterday": "Dün",
        "back": "Geri", "invalidName": "Lütfen bir ad girin",
        "invalidLang": "Lütfen bir dil seçin",
        "translationUnavailable": "Çeviri kullanılamıyor",
        "poweredBy": "DeepSeek (ücretsiz) ile çevrildi",
        "joinCta": "Katıl", "searchLanguages": "Dil ara…",
    },
    "pl": {
        "tagline": "Czatuj w każdym języku", "yourName": "Twoje imię",
        "namePlaceholder": "np. Maria", "selectLanguage": "Wybierz swój język",
        "languagePlaceholder": "Szukaj języków…", "createRoom": "Utwórz pokój",
        "joinRoom": "Dołącz do pokoju", "joinTitle": "Dołącz do pokoju",
        "joinSubtitle": "Wpisz kod pokoju, aby czatować", "roomCode": "Kod pokoju",
        "shareTitle": "Zaproś osoby", "shareSubtitle": "Udostępnij ten link — każdy wybiera swój język",
        "copyLink": "Kopiuj link zaproszenia", "copied": "Skopiowano!",
        "members": "Członkowie", "you": "Ty", "online": "online",
        "messagePlaceholder": "Napisz wiadomość…", "send": "Wyślij",
        "typing": "pisze…", "showOriginal": "Pokaż oryginał",
        "hideOriginal": "Ukryj oryginał", "original": "Oryginał",
        "translated": "Przetłumaczono", "leave": "Wyjdź",
        "connecting": "Łączenie…", "disconnected": "Rozłączono",
        "reconnect": "Połącz ponownie", "welcome": "Witaj w pokoju",
        "shareHint": "Udostępnij link, by znajomi dołączyli w swoim języku",
        "justNow": "przed chwilą", "today": "Dzisiaj", "yesterday": "Wczoraj",
        "back": "Wstecz", "invalidName": "Wpisz imię",
        "invalidLang": "Wybierz język",
        "translationUnavailable": "Tłumaczenie niedostępne",
        "poweredBy": "Tłumaczone przez DeepSeek (za darmo)",
        "joinCta": "Wejdź", "searchLanguages": "Szukaj języków…",
    },
    "sv": {
        "tagline": "Chatta på alla språk", "yourName": "Ditt namn",
        "namePlaceholder": "t.ex. Maria", "selectLanguage": "Välj ditt språk",
        "languagePlaceholder": "Sök språk…", "createRoom": "Skapa rum",
        "joinRoom": "Gå med i rum", "joinTitle": "Gå med i ett rum",
        "joinSubtitle": "Ange en rums-kod för att börja chatta", "roomCode": "Rums-kod",
        "shareTitle": "Bjud in personer", "shareSubtitle": "Dela denna länk — var och en väljer sitt språk",
        "copyLink": "Kopiera inbjudningslänk", "copied": "Kopierat!",
        "members": "Medlemmar", "you": "Du", "online": "online",
        "messagePlaceholder": "Skriv ett meddelande…", "send": "Skicka",
        "typing": "skriver…", "showOriginal": "Visa original",
        "hideOriginal": "Dölj original", "original": "Original",
        "translated": "Översatt", "leave": "Lämna",
        "connecting": "Ansluter…", "disconnected": "Frånkopplad",
        "reconnect": "Anslut igen", "welcome": "Välkommen till rummet",
        "shareHint": "Dela länken så att vänner kan gå med på sitt språk",
        "justNow": "nyss", "today": "Idag", "yesterday": "Igår",
        "back": "Tillbaka", "invalidName": "Ange ett namn",
        "invalidLang": "Välj ett språk",
        "translationUnavailable": "Översättning otillgänglig",
        "poweredBy": "Översatt av DeepSeek (gratis)",
        "joinCta": "Gå med", "searchLanguages": "Sök språk…",
    },
}

# Cache for languages translated on demand through the AI.
_AI_CACHE: Dict[str, dict] = {}


def _merge(code: str) -> dict:
    base = dict(EN)
    if code in BUILTIN:
        base.update(BUILTIN[code])
    return base


async def get_ui(lang: str) -> dict:
    if not lang or lang == "en":
        return dict(EN)
    if lang in BUILTIN:
        return _merge(lang)
    if lang in _AI_CACHE:
        return _AI_CACHE[lang]
    target = languages.language_name(lang)
    result = await translation.translator.translate_json(EN, target)
    merged = dict(EN)
    merged.update(result)
    _AI_CACHE[lang] = merged
    return merged
